version: '3.2'
services:
  mongodb:
    image: docker.io/mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    command: "mongod --auth"
volumes:
    mongodb_data:
