version: '3.2'
services:
  shlink:
    image: docker.io/shlinkio/shlink:stable
    networks:
      - traefik-public
    volumes:
      - shlink_data:/etc/shlink/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        
        # http redirection config
        - traefik.http.routers.shlink-http.rule=Host(`tny.erwijet.com`)
        - traefik.http.routers.shlink-http.entrypoints=http
        - traefik.http.routers.shlink-http.middlewares=https-redirect
        
        # https config
        - traefik.http.routers.shlink-https.rule=Host(`tny.erwijet.com`)
        - traefik.http.routers.shlink-https.entrypoints=https
        - traefik.http.routers.shlink-https.tls=true
        - traefik.http.routers.shlink-https.tls.certresolver=le
        
        # load-balencer config
        - traefik.http.services.shlink.loadbalancer.server.port=8080

networks:
  traefik-public:
    external: true
volumes:
  shlink_data:
